### ISSUE TITLE
[BUG] 3.0 Segmentation fault on some messages (core dump attached)

### ISSUE THREAD

**Issue by himpierre** [rspamd/rspamd#3871]
*Describe the bug**
After upgrading to 3.0 rspamd segmentation faults randomly on some messages.

2021-08-29 17:38:06 #21242(normal) <a02f21>; task; rspamd_message_parse: loaded message; id: <4f525168-5e7c-fa37-9232-f197fcac0a5a@domain.com>; queue-id: <1mKMso-0005XL-9x>; size: 6669; checksum: <935b9940bed956189da93c4df2d05aa2>
2021-08-29 17:38:06 #21242(normal) rspamd_crash_sig_handler: caught fatal signal 11(Segmentation fault), pid: 21242, trace: 
2021-08-29 17:38:06 #21242(normal) rspamd_crash_sig_handler: please see Rspamd FAQ to learn how to dump core files and how to fill a bug report

### Steps to Reproduce

1. Upgrade to 3.0 from 2.7
2. Random Segmentation Faults on some messages

**Expected behavior**
No segmentation faults

### Versions

Rspamd 3.0 
Gentoo

**Comment by himpierre** [comment]
It has been reported here https://bugs.gentoo.org/810337 compiling without jemalloc support fixes the issue. I'm testing it right now.

**Comment by himpierre** [comment]
Running without jemalloc support fixed the issue for me too.

**Comment by marcin-github** [comment]
backtrace with symbols
```
# gdb -q /usr/bin/rspamd 'core-1630328204-122-11-!usr!bin!rspamd-3.0-19161'
Reading symbols from /usr/bin/rspamd...
Reading symbols from /usr/lib/debug//usr/bin/rspamd-3.0.debug...

warning: Can't open file /dev/zero (deleted) during file-backed mapping note processing

warning: core file may not match specified executable file.
[New LWP 19161]
[Thread debugging using libthread_db enabled]                                                                                                                                                                 Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `rspamd: controller process (*:11334)                                          '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  atomic_load_p (mo=atomic_memory_order_relaxed, a=0xe2390) at /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/include/jemalloc/internal/atomic_gcc_atomic.h:31
31      /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/include/jemalloc/internal/atomic_gcc_atomic.h: No such file or directory.
(gdb) bt
#0  atomic_load_p (mo=atomic_memory_order_relaxed, a=0xe2390) at /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/include/jemalloc/internal/atomic_gcc_atomic.h:31
#1  rtree_leaf_elm_bits_read (dependent=true, elm=0xe2390, rtree=<optimized out>, tsdn=0x7f7c13afa6b8) at /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/include/jemalloc/internal/rtree.h:175
#2  rtree_leaf_elm_extent_read (dependent=true, elm=0xe2390, rtree=<optimized out>, tsdn=0x7f7c13afa6b8)
    at /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/include/jemalloc/internal/rtree.h:214
#3  rtree_extent_read (dependent=true, key=<optimized out>, rtree_ctx=<optimized out>, rtree=<optimized out>, tsdn=0x7f7c13afa6b8)
    at /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/include/jemalloc/internal/rtree.h:423
#4  iealloc (ptr=<optimized out>, tsdn=0x7f7c13afa6b8) at /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/include/jemalloc/internal/jemalloc_internal_inlines_b.h:83
#5  je_tcache_bin_flush_small (tsd=tsd@entry=0x7f7c13afa6b8, tcache=tcache@entry=0x7f7c13afa8a8, tbin=0x7f7c13afa900, binind=<optimized out>, rem=<optimized out>)
    at /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/src/tcache.c:152
#6  0x00007f7c17016c19 in tcache_dalloc_small (slow_path=false, binind=<optimized out>, ptr=0x55b79c47c150, tcache=<optimized out>, tsd=<optimized out>)
    at /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/include/jemalloc/internal/tcache_inlines.h:179
#7  arena_sdalloc (slow_path=false, alloc_ctx=0x0, tcache=<optimized out>, size=<optimized out>, ptr=0x55b79c47c150, tsdn=<optimized out>)
    at /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/include/jemalloc/internal/arena_inlines_b.h:420
#8  isdalloct (slow_path=false, alloc_ctx=0x0, tcache=<optimized out>, size=<optimized out>, ptr=0x55b79c47c150, tsdn=<optimized out>)
    at /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/include/jemalloc/internal/jemalloc_internal_inlines_c.h:131
#9  isfree (slow_path=false, tcache=<optimized out>, usize=<optimized out>, ptr=0x55b79c47c150, tsd=<optimized out>) at /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/src/jemalloc.c:2644
#10 je_sdallocx_default (ptr=0x55b79c47c150, size=48, flags=flags@entry=0) at /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/src/jemalloc.c:3583
#11 0x00007f7c170176d5 in je_je_sdallocx_noflags (ptr=ptr@entry=0x55b79c47c150, size=size@entry=48) at /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/src/jemalloc.c:3611
#12 0x00007f7c17045cae in operator delete (ptr=ptr@entry=0x55b79c47c150, size=size@entry=48) at /var/tmp/portage/dev-libs/jemalloc-5.2.1/work/jemalloc-5.2.1/src/jemalloc_cpp.cpp:131
#13 0x00007f7c18085ace in __gnu_cxx::new_allocator<std::_List_node<rspamd::css::css_parser_token> >::deallocate (__t=1, __p=0x55b79c47c150, this=0x55b79c47b910)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/ext/new_allocator.h:120
#14 std::allocator_traits<std::allocator<std::_List_node<rspamd::css::css_parser_token> > >::deallocate (__n=1, __p=0x55b79c47c150, __a=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/alloc_traits.h:492
#15 std::__cxx11::_List_base<rspamd::css::css_parser_token, std::allocator<rspamd::css::css_parser_token> >::_M_put_node (__p=0x55b79c47c150, this=0x55b79c47b910)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/stl_list.h:446
#16 std::__cxx11::list<rspamd::css::css_parser_token, std::allocator<rspamd::css::css_parser_token> >::_M_erase (__position=..., this=0x55b79c47b910)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/stl_list.h:1930
#17 std::__cxx11::list<rspamd::css::css_parser_token, std::allocator<rspamd::css::css_parser_token> >::pop_front (this=0x55b79c47b910)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/stl_list.h:1198
#18 rspamd::css::css_tokeniser::next_token (this=0x55b79c47b8f0) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/css/css_tokeniser.cxx:427
#19 0x00007f7c1808d5be in rspamd::css::css_parser::component_value_consumer (this=0x7ffef64aded0, top=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/g++-v10/bits/unique_ptr.h:173
#20 0x00007f7c18090d58 in rspamd::css::css_parser::consume_css_rule (this=0x7ffef64aded0, sv=...) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/css/css_parser.cxx:599
#21 0x00007f7c18090e77 in rspamd::css::get_rules_parser_functor (pool=<optimized out>, st=...) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/css/css_parser.cxx:756
#22 0x00007f7c1809117a in rspamd::css::parse_css_declaration (pool=pool@entry=0x55b79c3a2a60, st=...) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/css/css_parser.cxx:819
#23 0x00007f7c1805047d in rspamd::html::html_process_block_tag (hc=<optimized out>, tag=<optimized out>, pool=0x55b79c3a2a60)
    at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/html/html.cxx:962
#24 operator() (__closure=0x7ffef64ae1f0) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/html/html.cxx:1441
#25 0x00007f7c18051409 in rspamd::html::html_process_input (pool=<optimized out>, in=<optimized out>, exceptions=<optimized out>, url_set=<optimized out>, part_urls=<optimized out>,
    allow_css=<optimized out>) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/html/html.cxx:1808
#26 0x00007f7c180ad485 in rspamd_message_process_html_text_part (text_part=0x55b79c3e4140, task=0x55b79c3a2b00) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libmime/message.c:767
#27 rspamd_message_process_text_part_maybe (mime_part=0x55b79c3e3988, task=0x55b79c3a2b00) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libmime/message.c:838
#28 rspamd_message_process (task=task@entry=0x55b79c3a2b00) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libmime/message.c:1497
#29 0x00007f7c1802454e in rspamd_task_process (task=0x55b79c3a2b00, stages=131071) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/task.c:741
#30 0x00007f7c18024433 in rspamd_task_process (task=0x55b79c3a2b00, stages=131071) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/task.c:883
#31 0x00007f7c18024433 in rspamd_task_process (task=0x55b79c3a2b00, stages=131071) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/task.c:883
#32 0x00007f7c18024433 in rspamd_task_process (task=task@entry=0x55b79c3a2b00, stages=stages@entry=131071) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/task.c:883
#33 0x000055b799ed0dbd in rspamd_controller_handle_scan (conn_ent=0x55b79c3ab3f0, msg=0x55b79c39a760) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/controller.c:2178
#34 0x00007f7c1803ab78 in rspamd_http_router_finish_handler (conn=<optimized out>, msg=0x55b79c39a760) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/http/http_router.c:343
#35 0x00007f7c18038d29 in rspamd_http_on_message_complete (parser=<optimized out>) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/http/http_connection.c:697
#36 0x00007f7c1812dfcf in http_parser_execute (parser=parser@entry=0x55b79c3abe48, settings=settings@entry=0x55b79c3abe68,
    data=0x55b79c34b470 "\ntarget=3D\"_blank\"><img align=3D\"center\" alt=3D\"KUP TERAZ\" src=3D\"https://re=\nsources.in.bedigital.pl/packages/package_612621d338e87/qi2.jpg\" style=3D\"ma=\nrgin: 0 auto; display: block; border: 0;\" val"..., len=len@entry=3254) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/contrib/http-parser/http_parser.c:1773
#37 0x00007f7c18039974 in rspamd_http_event_handler (fd=<optimized out>, what=<optimized out>, ud=0x55b79c3aa700)
    at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/http/http_connection.c:953
#38 0x00007f7c17a14cb5 in ev_invoke_pending (loop=0x55b79c1849b0) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/contrib/libev/ev.c:3807
#39 0x00007f7c17a18a16 in ev_run (flags=0, loop=0x55b79c1849b0) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/contrib/libev/ev.c:4228
#40 ev_run (loop=0x55b79c1849b0, flags=flags@entry=0) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/contrib/libev/ev.c:4058
#41 0x000055b799ece6f0 in ev_loop (flags=0, loop=<optimized out>) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/contrib/libev/ev.h:830
--Type <RET> for more, q to quit, c to continue without paging--
#42 start_controller_worker (worker=0x55b79c07a980) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/controller.c:4111
#43 0x00007f7c1802e9b1 in rspamd_handle_child_fork (listen_sockets=<optimized out>, cf=0x55b79ae94f30, rspamd_main=0x55b79adb2ca0, wrk=0x55b79c07a980)
    at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/worker_util.c:1183
#44 rspamd_fork_worker (rspamd_main=0x55b79adb2ca0, cf=0x55b79ae94f30, index=<optimized out>, ev_base=<optimized out>, term_handler=term_handler@entry=0x55b799ed9460 <rspamd_cld_handler>,
    listen_sockets=<optimized out>) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/libserver/worker_util.c:1282
#45 0x000055b799ed9430 in rspamd_fork_delayed_cb (loop=<optimized out>, w=<optimized out>, revents=<optimized out>) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/rspamd.c:367
#46 0x00007f7c17a14cb5 in ev_invoke_pending (loop=0x7f7c17a20720 <default_loop_struct>) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/contrib/libev/ev.c:3807
#47 0x00007f7c17a18a16 in ev_run (flags=0, loop=0x7f7c17a20720 <default_loop_struct>) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/contrib/libev/ev.c:4228
#48 ev_run (loop=loop@entry=0x7f7c17a20720 <default_loop_struct>, flags=flags@entry=0) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/contrib/libev/ev.c:4058
#49 0x000055b799ecbdbe in ev_loop (flags=0, loop=0x7f7c17a20720 <default_loop_struct>) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/contrib/libev/ev.h:830
#50 main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at /usr/src/debug/mail-filter/rspamd-3.0-r2/rspamd-3.0/src/rspamd.c:1616
(gdb)
```

**Comment by arkamar** [comment]
I did a git bisect and it started to segfault in one of following commits (I skipped 2bf132355056 - d734f2119237 because of compilation errors):

- 6c1822676cb7 - `[Rework] Html: Rework lua bindings`
- d734f2119237 - `[Rework] Html: Convert to variant`
- 71d6269deafc - `[Rework] Html: Final rework part for the html processing code`
- a7496ccc1eb5 - `[Rework] Html: Move blocks part`
- b6a4d1a2edc0 - `[Rework] Html: Move images processing stuff`
- 882ea3395af8 - `[Rework] Html: Further html urls rework`
- 2bf132355056 - `[Rework] Html: Start refactoring of the html tags handling`

I bisected it with `jemalloc` enabled and tested it with `rspamc test/functional/messages/*.eml`. Last working commit is c9a5719fb618 - `[Minor] Add another helper for mempool typed allocations`.

**Comment by vstakhov** [comment]
Is there a message that can reproduce this bug? I have quite a strict asan build that can detect all types of memory issues but I need to know all steps to reproduce it locally.

**Comment by vstakhov** [comment]
Jemalloc is not a culprit btw, the memory corruption takes place somewhere else, so the best option is to test asan packages with the same configuration.

**Comment by arkamar** [comment]
I am in the most recent commit in `master` branch 355ccaca3c2f - `[Fix] Delete the correct pointer type`

The build is configured this way:
```
cmake -C /var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCONFDIR=/etc/rspamd -DRUNDIR=/var/run/rspamd -DDBDIR=/var/lib/rspamd -DLOGDIR=/var/log/rspamd -DSYSTEM_FMT=ON -DSYSTEM_ZSTD=ON -DENABLE_BLAS=OFF -DENABLE_HYPERSCAN=ON -DENABLE_JEMALLOC=ON -DENABLE_LUAJIT=OFF -DENABLE_PCRE2=OFF -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999_build /gentoo_toolchain.cmake  /var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999
```
For `-DENABLE_JEMALLOC=OFF` everything works as expected. I use default configuration in `/etc/rspamd` as it is installed.

This is the test I run with the same result every time:

```
~/rspamd % rspamc test/functional/messages/bad_message.eml
Results for file: test/functional/messages/bad_message.eml (0.044 seconds)
IO read error: unexpected EOF
```

And those are related lines from `rspamd`:

```
2021-08-31 09:28:49 #17238(controller) <imhkkk>; monitored; rspamd_monitored_dns_cb: DNS query blocked on multi.uribl.com (127.0.0.1 returned), possibly due to high volume
2021-08-31 09:29:01 #17238(controller) <0c1684>; csession; rspamd_controller_check_password: allow unauthorized connection from a trusted IP 127.0.0.1
2021-08-31 09:29:01 #17238(controller) <0c1684>; csession; rspamd_message_parse: loaded message; id: <588d01d0b859$92a6a7e0$10a887d3@nasutkadqw>; queue-id: <undef>; size: 316468; checksum: <d5ffc4bc8fe32606160b825eacaca8d5>
2021-08-31 09:29:01 #17238(controller) <0c1684>; csession; rspamd_mime_text_part_utf8_convert: converted text part from ibm-5347_P100-1998 ('windows-1251' announced) to UTF-8 inlen: 27, outlen: 27 (27 UTF16 chars)
2021-08-31 09:29:01 #17238(controller) <0c1684>; csession; rspamd_mime_text_part_utf8_convert: converted text part from ibm-5347_P100-1998 ('windows-1251' announced) to UTF-8 inlen: 4181, outlen: 4181 (4181 UTF16 chars)
2021-08-31 09:29:01 #17238(controller) rspamd_crash_sig_handler: caught fatal signal 11(Segmentation fault), pid: 17238, trace:
2021-08-31 09:29:01 #17238(controller) rspamd_crash_sig_handler: please see Rspamd FAQ to learn how to dump core files and how to fill a bug report
2021-08-31 09:29:01 #17236(main) <1faa78>; main; rspamd_check_termination_clause: controller process 17238 terminated abnormally with exit code 0 by signal: Segmentation fault but NOT created core file (throttled=no); core file limits: 0 current, -1 max
2021-08-31 09:29:01 #17236(main) <1faa78>; main; rspamd_cld_handler: respawn process controller in lieu of terminated process with pid 17238
2021-08-31 09:29:03 #17236(main) <1faa78>; main; rspamd_fork_worker: prepare to fork process controller (0); listen on: localhost:11334
2021-08-31 09:29:03 #17269(controller) <1faa78>; main; rspamd_worker_set_limits: use system max file descriptors limit: 1024B cur and 4KiB max
2021-08-31 09:29:03 #17269(controller) <1faa78>; main; rspamd_worker_set_limits: use system max core size limit: 0B cur and -1B max
2021-08-31 09:29:03 #17269(controller) <1faa78>; main; rspamd_handle_child_fork: starting controller process 17269 (0); listen on: localhost:11334
2021-08-31 09:29:03 #17269(controller) <wm3szy>; controller; rspamd_controller_password_sane: your normal password is not encrypted, we strongly recommend to replace it with the encrypted one
2021-08-31 09:29:03 #17269(controller) <wm3szy>; controller; rspamd_controller_password_sane: enable password is not set, so you should filter controller availability by using of firewall or `secure_ip` option
```

**Comment by vstakhov** [comment]
I think this commit might fix your issue. Could you please test?

**Comment by arkamar** [comment]
No, this commit didn't fix the issue for me.

**Comment by vstakhov** [comment]
Gah, and what about this commit?

**Comment by arkamar** [comment]
No, this commit didn't fixed it either. Anyway, I thought you were able to reproduce the segfault but now it seems that you are just blindly trying to fix it. I think it would be better if someone else who really experiences the bug will do it. I may try it when I will have some time.

**Comment by vstakhov** [comment]
No, I cannot reproduce it. It seems to be related with specific libc++ behaviour. In theory, I have archlinux with the bleeding edge stuff, so I can try to test it there.

**Comment by arkamar** [comment]
Ok, I can test this hyphotesis by downgrading to older gcc.

**Comment by kam821** [comment]
@vstakhov 
It seems that change in css_tokeniser.hxx should work.
Before there was std::forward used on non-templated type, which sometimes causes wonderful mess.
You can always add additional overload, one for const reference as it is now, and second for rvalue reference.
```
auto pushback_token(const css_parser_token& t) const -> void {
	backlog.push_back(t);
}

auto pushback_token(css_parser_token&& t) const -> void {
	backlog.push_back(std::move(t));
}
```
Or make one function template and then std::forward
```
template <typename TokenT>
auto pushback_token(TokenT&& t) const -> void {
	backlog.push_back(std::forward<TokenT>(t));
}
```
However for the better "debuggability" templated type should be constrained by std::is_same_v/std::same_as concept but in this case I think it's overshoot and two overloads option is better.

**Comment by vstakhov** [comment]
I think I would just leave copying sollution as `css_parser_token` is trivially copyable. The problem that it doesn't fix the crash ¯\_(ツ)_/¯

**Comment by arkamar** [comment]
I tried to experiment with toolchain a little bit and it seems that the segfault is triggered by `-Wl,--as-needed` `LDFLAG`. Actually Gentoo uses `LDFLAGS="-Wl,-O1 -Wl,--as-needed"` by default but optimization flag does not affect it. I tested it with gcc-10.3.0, gcc-9.4.0 and `ld.gold` from binutils-2.35.2 and `ld.lld` (LLD 12.0.1 (compatible with GNU linkers)).

I also tried to compile it with `clang` version 12.0.1 and rspamd works as expected without segfaults for both linkers I mentioned above.

**Comment by vstakhov** [comment]
Then it seems like an ODR violation somewhere...

**Comment by erialor** [comment]
There seems to be an ODR here:
`/var/tmp/portage/mail-filter/rspamd-3.0-r4/work/rspamd-3.0/src/libserver/html/html.hxx:42:8: warning: type ‘struct html_content’ violates the C++ One Definition Rule [-Wodr]
   42 | struct html_content {
      |        ^
/var/tmp/portage/mail-filter/rspamd-3.0-r4/work/rspamd-3.0/src/libserver/html/html.hxx:42:8: note: a different type is defined in another translation unit
   42 | struct html_content {
      |        ^
/var/tmp/portage/mail-filter/rspamd-3.0-r4/work/rspamd-3.0/src/libserver/html/html.hxx:47:35: note: the first difference of corresponding definitions is field  images’
   47 |         std::vector<html_image *> images;
      |                                   ^
/var/tmp/portage/mail-filter/rspamd-3.0-r4/work/rspamd-3.0/src/libserver/html/html.hxx:47:35: note: a field of same name but different type is defined in another translation unit
   47 |         std::vector<html_image *> images;
      |                                   ^
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/g++-v11/bits/stl_vector.h:389:11: note: type name ‘std::vector<html_image*, std::allocator<html_image*> >’ should match type name ‘std::vector<rspamd::html::html_image*, std::allocator<rspamd::html::html_image*> >’
  389 |     class vector : protected _Vector_base<_Tp, _Alloc>
      |           ^
/var/tmp/portage/mail-filter/rspamd-3.0-r4/work/rspamd-3.0/src/libserver/html/html_tag.hxx:85:8: warning: type ‘struct html_tag’ violates the C++ One Definition Rule [-Wodr]
   85 | struct html_tag {
      |        ^
/var/tmp/portage/mail-filter/rspamd-3.0-r4/work/rspamd-3.0/src/libserver/html/html_tag.hxx:85:8: note: a different type is defined in another translation unit
   85 | struct html_tag {
      |        ^
/var/tmp/portage/mail-filter/rspamd-3.0-r4/work/rspamd-3.0/src/libserver/html/html_tag.hxx:94:26: note: the first difference of corresponding definitions is field ‘extra’
   94 |         html_tag_extra_t extra;
      |                          ^
/var/tmp/portage/mail-filter/rspamd-3.0-r4/work/rspamd-3.0/src/libserver/html/html_tag.hxx:94:26: note: a field of same name but different type is defined in another translation unit
   94 |         html_tag_extra_t extra;
      |                          ^
/var/tmp/portage/mail-filter/rspamd-3.0-r4/work/rspamd-3.0/src/libserver/html/html_tag.hxx:85:8: note: type name ‘std::variant<std::monostate, rspamd_url*, html_image*>’ should match type name ‘std::variant<std::monostate, rspamd::html::rspamd_url*, rspamd::html::html_image*>’
   85 | struct html_tag {
      |        ^`

No idea if this could cause the segmentation fault?
Saw it while trying to build it w/o -Wl,--as-needed (which indeed fixes/works around the segfault issue)

**Comment by renaudallard** [comment]
This bug is still present in OpenBSD for rspamd 3.2. I compiled it with -DENABLE_JEMALLOC=OFF but that didn't seem to solve the issue either.
