### ISSUE TITLE
[BUG] Fails to build with libfmt 10.0.0

### ISSUE THREAD

**Issue by candrews** [rspamd/rspamd#4482]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Compiling rspamd 3.5 against [libfmt 10.0.0](https://github.com/fmtlib/fmt/releases/tag/10.0.0) fails. The compilation error is:
```
In file included from /var/tmp/portage/mail-filter/rspamd-3.5/work/rspamd-3.5/src/libserver/symcache/symcache_item.cxx:20:
/usr/include/fmt/core.h: In instantiation of ‘constexpr decltype (ctx.begin()) fmt::v10::detail::parse_format_specs(ParseContext&) [with T = rspamd_symbol_type; ParseContext = compile_parse_context<char>; decltype (ctx.begin()) = const char*]’:
/usr/include/fmt/core.h:2620:22:   required from ‘constexpr fmt::v10::detail::format_string_checker<Char, Args>::format_string_checker(fmt::v10::basic_string_view<Char>) [with Char = char; Args = {rspamd_symbol_type}]’
/var/tmp/portage/mail-filter/rspamd-3.5/work/rspamd-3.5/src/libserver/symcache/symcache_item.cxx:602:41:   required from here
/usr/include/fmt/core.h:2561:10: error: use of deleted function ‘fmt::v10::formatter<T, Char, Enable>::formatter() [with T = rspamd_symbol_type; Char = char; Enable = void]’
 2561 |   return formatter<mapped_type, char_type>().parse(ctx);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/fmt/core.h:792:3: note: declared here
  792 |   formatter() = delete;
      |   ^~~~~~~~~
/usr/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_value(T&&) [with Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = rspamd_symbol_type&]’:
/usr/include/fmt/core.h:1711:29:   required from ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; type <anonymous> = fmt::v10::detail::type::custom_type; T = rspamd_symbol_type&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]’
/usr/include/fmt/core.h:1827:77:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {rspamd_symbol_type&}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {rspamd_symbol_type}]’
/usr/include/fmt/core.h:1844:31:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T&& ...) [with Context = basic_format_context<appender, char>; T = {rspamd_symbol_type&}]’
/usr/include/fmt/core.h:2817:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {rspamd_symbol_type&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, rspamd_symbol_type&>]’
/var/tmp/portage/mail-filter/rspamd-3.5/work/rspamd-3.5/src/libserver/symcache/symcache_item.cxx:602:41:   required from here
/usr/include/fmt/core.h:1691:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1691 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1691:7: note: ‘formattable’ evaluates to false
```
[build.log](https://github.com/rspamd/rspamd/files/11443248/build.log)

### Steps to Reproduce

1. Install libfmt 10.0.0
2. Build rspamd

**Expected behavior**
Successful compilation

### Versions

* rpsamd 3.5
* linux 6.3.0
* gcc (Gentoo 13.1.0-r1 p1) 13.1.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by arkamar** [comment]
after a6c019c fix the error message has changed to:
```
FAILED: src/CMakeFiles/rspamd-server.dir/libserver/symcache/symcache_item.cxx.o
/usr/bin/x86_64-pc-linux-gnu-g++ -DDOCTEST_CONFIG_NO_MULTI_LANE_ATOMICS -DDOCTEST_CONFIG_USE_STD_HEADERS -DFMT_HEADER_ONLY -DHAVE_CONFIG_H -DSYS_ZSTD -DU_CHARSET_IS_UTF8 -Drspamd_server_EXPORTS -I/var/tmp/portage/mail-filter/rspamd-9999/wo
rk/rspamd-9999/contrib/hiredis -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999 -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libutil -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libserver -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libmime -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libstat -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libcryptobox -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/libucl -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/replxx/include -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/uthash -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/http-parser -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/fpconv -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/libottery -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/cdb -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/librdns -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/aho-corasick -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/lc-btrie -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/lua-lpeg -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/frozen/include -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/fu2/include -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999_build/src -I/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999_build/src/libcryptobox -I/usr/include/luajit-2.1 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/hs  -O2 -pipe -std=gnu++20 -fPIC -msse2 -m64 -D_GNU_SOURCE -DLINUX -Wextra -Wall -Wpointer-arith -Wno-unused-parameter -Wno-unused-function -Wunused-variable -Wno-strict-aliasing -fno-strict-aliasing -Wnull-dereference -Wduplicated-cond -Wno-unused-const-variable -Wno-sign-compare -Wno-implicit-fallthrough -Wmissing-noreturn -Wmissing-format-attribute -Wno-deprecated-declarations -fPIC -MD -MT src/CMakeFiles/rspamd-server.dir/libserver/symcache/symcache_item.cxx.o -MF src/CMakeFiles/rspamd-server.dir/libserver/symcache/symcache_item.cxx.o.d -o src/CMakeFiles/rspamd-server.dir/libserver/symcache/symcache_item.cxx.o -c /var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libserver/symcache/symcache_item.cxx
In file included from /var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libserver/symcache/symcache_item.cxx:20:
/usr/include/fmt/core.h: In instantiation of ‘constexpr decltype (ctx.begin()) fmt::v10::detail::parse_format_specs(ParseContext&) [with T = rspamd_symbol_type; ParseContext = compile_parse_context<char>; decltype (ctx.begin()) = const char*]’:
/usr/include/fmt/core.h:2620:22:   required from ‘constexpr fmt::v10::detail::format_string_checker<Char, Args>::format_string_checker(fmt::v10::basic_string_view<Char>) [with Char = char; Args = {rspamd_symbol_type}]’
/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libserver/symcache/symcache_item.cxx:575:43:   required from ‘rspamd::symcache::item_type_from_c(rspamd_symbol_type)::<lambda(auto:57, rspamd::symcache::symcache_item_type)> [with auto:57 = rspamd_symbol_type]’
/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libserver/symcache/symcache_item.cxx:581:24:   required from here
/usr/include/fmt/core.h:2561:10: error: use of deleted function ‘fmt::v10::formatter<T, Char, Enable>::formatter() [with T = rspamd_symbol_type; Char = char; Enable = void]’
 2561 |   return formatter<mapped_type, char_type>().parse(ctx);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/fmt/core.h:792:3: note: declared here
  792 |   formatter() = delete;
      |   ^~~~~~~~~
/usr/include/fmt/core.h: In instantiation of ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_value(T&&) [with Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = rspamd_symbol_type&]’:
/usr/include/fmt/core.h:1711:29:   required from ‘constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; type <anonymous>
= fmt::v10::detail::type::custom_type; T = rspamd_symbol_type&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]’
/usr/include/fmt/core.h:1827:77:   required from ‘constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {rspamd_symbol_type&}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {rspamd_symbol_type}]’
/usr/include/fmt/core.h:1844:31:   required from ‘constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T&& ...) [with Context = basic_format_context<appender, char>; T = {rspamd_symbol_type&}]’
/usr/include/fmt/core.h:2817:44:   required from ‘std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {rspamd_symbol_type&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, rspamd_symbol_type&>]’
/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libserver/symcache/symcache_item.cxx:575:43:   required from ‘rspamd::symcache::item_type_from_c(rspamd_symbol_type)::<lambda(auto:57, rspamd::symcache::symcache_item_type)> [with auto:57 = rspamd_symbol_type]’
/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libserver/symcache/symcache_item.cxx:581:24:   required from here
/usr/include/fmt/core.h:1691:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1691 |       formattable,
      |       ^~~~~~~~~~~
/usr/include/fmt/core.h:1691:7: note: ‘formattable’ evaluates to false
```

**Comment by vstakhov** [comment]
That's exactly the same issue I'm afraid... I'm testing Rspamd with the bundled `fmt` so it's quite hard for me to check the corner cases.

**Comment by arkamar** [comment]
rspamd-3.6 seems to work with libfmt-10, compiled with gcc version 13.2.0 (Gentoo 13.2.0 p3).
