### ISSUE TITLE
Assertion failure after upgrade to 1.9.0

### ISSUE THREAD

**Issue by Elwisz** [rspamd/rspamd#2787]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
rspamd_1.9.0-1~stretch_amd64.deb

### Operation system (the exact version), CPU (including architecture and processor family):
Debian 9.8

### Description (Please provide a descriptive summary of the issue):
After upgrading to 1.9.0, rspam fails to start because of an assertion failure.

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):
2019-03-13 07:58:11 #6066(main) <mmfkhm>; cfg; rspamd_map_parse_backend: map '/etc/rspamd/local.d/redirectors.inc' is not found, but it can be loaded automatically later
2019-03-13 07:58:11 #6066(main) <mmfkhm>; cfg; rspamd_init_lua_filters: init lua module phishing
2019-03-13 07:58:11 #6066(main) <mmfkhm>; lua; ratelimit.lua:836: no servers are specified, disabling module
2019-03-13 07:58:11 #6066(main) <mmfkhm>; cfg; rspamd_init_lua_filters: init lua module ratelimit
2019-03-13 07:58:11 #6066(main) <mmfkhm>; cfg; rspamd_register_symbol_fromlua: duplicate symbol: RECEIVED_SPAMHAUS, skip registering
2019-03-13 07:58:11 #6066(main) <mmfkhm>; symcache; rspamd_symcache_add_symbol: no parent symbol is associated with virtual symbol RECEIVED_SPAMHAUS_CSS
2019-03-13 07:58:11 #6066(main) glib; rspamd_glib_printerr_function: **
ERROR:/rspamd-1.9.0/src/libserver/rspamd_symcache.c:953:rspamd_symcache_add_symbol: assertion failed: (parent != -1)

2019-03-13 07:58:12 #6090(main) lua; lua_cfg_transform.lua:160: group excessqp has no symbols
2019-03-13 07:58:12 #6090(main) lua; lua_cfg_transform.lua:160: group excessb64 has no symbols

**Comment by Elwisz** [comment]
Solved. In my local.d/rbl.conf I had an entry named "spamhaus_xbl" that seems to have been renamed to "spamhaus_received" in some recent version of rspamd. After I renamed "spamhaus_xbl" to "spamhaus_received" accordingly, rspamd 1.9.0 now works without errors on startup.

As I don't know if this issue was my fault or if it is something that rspamd should have handled gracefully, I'm leaving this issue open for now for you to decide.
