### PR TITLE
fix: mime_string const iterator

### LINKED ISSUE #5994: [BUG] Build fail with doctest 2.5.0
Hi,

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

When bumping doctest from 2.4.12 to 2.5.0 in nixpkgs, build fail with:

```cpp
[ 76%] Building CXX object src/CMakeFiles/rspamd-server.dir/libmime/mime_string.cxx.o
In file included from /build/source/src/libmime/mime_string.cxx:18:
/nix/store/4j70hhbg5xmlfspb1pfbcw49glsrm1jj-doctest-2.5.0/include/doctest/doctest.h: In instantiation of 'static void doctest::detail::filldata<T, typename std::enable_if<((! doctest::detail::has_insertion_operator<T>::value) && doctest::detail::is_container<T>::value)>::type>::fill(std::ostream*, const T&) [with T = rspamd::mime::basic_mime_string<char>; std::ostream = std::basic_ostream<char>]':
/nix/store/4j70hhbg5xmlfspb1pfbcw49glsrm1jj-doctest-2.5.0/include/doctest/doctest.h:1086:22:   required from 'void doctest::detail::filloss(std::ostream*, const T&) [with T = rspamd::mime::basic_mime_string<char>; std::ostream = std::basic_ostream<char>]'
 1086 |     filldata<T>::fill(stream, in);
      |     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/nix/store/4j70hhbg5xmlfspb1pfbcw49glsrm1jj-doctest-2.5.0/include/doctest/doctest.h:1099:12:   required from 'doctest::String doctest::detail::toStream(const T&) [with T = rspamd::mime::basic_mime_string<char>]'
 1099 |     filloss(stream, in);
      |     ~~~~~~~^~~~~~~~~~~~
/nix/store/4j70hhbg5xmlfspb1pfbcw49glsrm1jj-doctest-2.5.0/include/doctest/doctest.h:1107:24:   required from 'static doctest::String doctest::detail::StringMakerBase<true>::convert(const T&) [with T = rspamd::mime::basic_mime_string<char>]'
 1107 |         return toStream(in);
      |                ~~~~~~~~^~~~
/nix/store/4j70hhbg5xmlfspb1pfbcw49glsrm1jj-doctest-2.5.0/include/doctest/doctest.h:1144:35:   required from 'doctest::String doctest::toString(const T&) [with T = rspamd::mime::basic_mime_string<char>; typename std::enable_if<(! detail::should_stringify_as_underlying_type<T>::value), bool>::type <anonymous> = true]'
 1144 |     return StringMaker<T>::convert(value);
      |            ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/nix/store/4j70hhbg5xmlfspb1pfbcw49glsrm1jj-doctest-2.5.0/include/doctest/doctest.h:1290:13:   required from 'doctest::String doctest::detail::stringifyBinaryExpr(const L&, const char*, const R&) [with L = rspamd::mime::basic_mime_string<char>; R = char [1]]'
 1290 |     return (DOCTEST_STRINGIFY(lhs)) + op + (DOCTEST_STRINGIFY(rhs));
      |             ^
/nix/store/4j70hhbg5xmlfspb1pfbcw49glsrm1jj-doctest-2.5.0/include/doctest/doctest.h:2000:5:   required from 'decltype (((void)((declval<L>() == declval<R>())), (doctest::detail::Result)(<brace-enclosed initializer list>()))) doctest::detail::Expression_lhs<L>::operator==(R&&) [with R = const char (&)[1]; L = const rspamd::mime::basic_mime_string<char>&; decltype (((void)((declval<L>() == declval<R>())), (doctest::detail::Result)(<brace-enclosed initializer list>()))) = doctest::detail::Result]'
 2000 |     DOCTEST_DO_BINARY_EXPRESSION_COMPARISON(==, " == ", DOCTEST_CMP_EQ)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/source/src/libmime/mime_string.cxx:31:4:   required from here
   31 |                         CHECK(st == "");
      |                                     ^~
/nix/store/4j70hhbg5xmlfspb1pfbcw49glsrm1jj-doctest-2.5.0/include/doctest/doctest.h:1277:32: error: passing 'const rspamd::mime::basic_mime_string<char>' as 'this' argument discards qualifiers [-fpermissive]
 1277 |         for (auto it = in.begin(); it != in.end(); ++it) {
      |                        ~~~~~~~~^~
In file included from /build/source/src/libmime/mime_string.cxx:19:
/build/source/src/libmime/mime_string.hxx:526:21: note:   in call to 'rspamd::mime::basic_mime_string<T, Allocator, Functor>::iterator rspamd::mime::basic_mime_string<T, Allocator, Functor>::begin() [with CharT = char; Allocator = std::allocator<char>; Functor = fu2::abi_400::detail::function<fu2::abi_400::detail::config<false, true, fu2::capacity_default>, fu2::abi_400::detail::property<true, false, int(int)> >; iterator = rspamd::mime::iterator<rspamd::mime::basic_mime_string<char>, false>]'
  526 |         inline auto begin() noexcept -> iterator
      |                     ^~~~~
/nix/store/4j70hhbg5xmlfspb1pfbcw49glsrm1jj-doctest-2.5.0/include/doctest/doctest.h:1277:48: error: passing 'const rspamd::mime::basic_mime_string<char>' as 'this' argument discards qualifiers [-fpermissive]
 1277 |         for (auto it = in.begin(); it != in.end(); ++it) {
      |                                          ~~~~~~^~
/build/source/src/libmime/mime_string.hxx:536:21: note:   in call to 'rspamd::mime::basic_mime_string<T, Allocator, Functor>::iterator rspamd::mime::basic_mime_string<T, Allocator, Functor>::end() [with CharT = char; Allocator = std::allocator<char>; Functor = fu2::abi_400::detail::function<fu2::abi_400::detail::config<false, true, fu2::capacity_default>, fu2::abi_400::detail::property<true, false, int(int)> >; iterator = rspamd::mime::iterator<rspamd::mime::basic_mime_string<char>, false>]'
  536 |         inline auto end() noexcept -> iterator
      |                     ^~~
/nix/store/4j70hhbg5xmlfspb1pfbcw49glsrm1jj-doctest-2.5.0/include/doctest/doctest.h:1278:31: error: passing 'const rspamd::mime::basic_mime_string<char>' as 'this' argument discards qualifiers [-fpermissive]
 1278 |             if (it != in.begin()) {
      |                       ~~~~~~~~^~
/build/source/src/libmime/mime_string.hxx:526:21: note:   in call to 'rspamd::mime::basic_mime_string<T, Allocator, Functor>::iterator rspamd::mime::basic_mime_string<T, Allocator, Functor>::begin() [with CharT = char; Allocator = std::allocator<char>; Functor = fu2::abi_400::detail::function<fu2::abi_400::detail::config<false, true, fu2::capacity_default>, fu2::abi_400::detail::property<true, false, int(int)> >; iterator = rspamd::mime::iterator<rspamd::mime::basic_mime_string<char>, false>]'
  526 |         inline auto begin() noexcept -> iterator
      |                     ^~~~~
make[2]: *** [src/CMakeFiles/rspamd-server.dir/build.make:2305: src/CMakeFiles/rspamd-server.dir/libmime/mime_string.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1848: src/CMakeFiles/rspamd-server.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

I already tried a few simple things, like adding another `inline auto begin() noexcept -> iterator` with more `const`, but it was not enough.

### Steps to Reproduce

1. build with doctest 2.5.0

**Expected behavior**

should build

### Versions

N/A

### Additional Information

N/A

### PR DESCRIPTION
**Pull request by xandris**
mime_string's iterator is just a value iterator anyway. it's intrinsically const. drop reference to const_iterator, let iterator_base take a const pointer, and mark begin() and end() as const.

doctest 2.5.0 receives a const reference so it can't use a mutable iterator, which leads to compile error.

resolves #5994

### CODE REVIEW

**Review by vstakhov — COMMENTED** [review]
## Review

The fix is correct and well-targeted — I'd approve after one small cleanup. The root cause in #5994 is real: doctest 2.5.0 stringifies containers through a `const T&`, so it calls `begin()`/`end()` on a const `basic_mime_string`, which failed because those methods were non-const. Making them `const` (and `cont_instance` a `const Container *`) is the right, minimal fix.

### Verified locally

Built the PR against the existing build's flags (`-Wall -Wextra`, clang):

- ✅ `mime_string.cxx` test TU compiles clean — zero warnings, including with `-Wdeprecated-copy -Wignored-qualifiers` added explicitly.
- ✅ `received.cxx` (the only other includer) compiles clean.
- ✅ Tests still exercise the path — `mime_string.cxx` iterates a non-const `st` via range-for / `raw_begin()`-`raw_end()`; calling now-const methods on a non-const object is fine.
- ✅ Dead-scaffolding removal is safe: `get_instance()` has no callers anywhere, and `const_iterator` was only ever forward-declared (never defined), used solely for the `= delete` guard.
- ✅ Const-only iterators are correct here — these are value iterators (return a codepoint by value), so there's nothing to mutate through them.

(Couldn't reproduce the original 2.5.0 failure since the repo bundles an older doctest in `contrib/`, but the fix directly addresses the const-correctness the error points to.)

### Please address

**1. (Must fix) Tabs vs. spaces — clang-format violation.** `src/libmime/mime_string.hxx:200-202` use 4 spaces instead of tabs:

```cpp
    using base = iterator_base<Container, Raw>;
    using typename base::difference_type;
    using typename base::reference_type;
```

Running `clang-format` rewrites exactly these three lines to tabs, so this will trip the format hook/CI. Re-indent with tabs.

**2. (Minor) Stray `const` on `end()`'s return type.** `src/libmime/mime_string.hxx:526`:

```cpp
inline auto end() const noexcept -> iterator const
```

The trailing `const` on a by-value return is meaningless and inconsistent with `begin()`/`raw_begin()`/`raw_end()`. Clang doesn't warn, but GCC's `-Wignored-qualifiers` (part of `-Wextra`) will emit "type qualifiers ignored on function return type" on CI. Looks like a copy/paste leftover — drop it: `-> iterator`.

**3. (Nit) Title/commit convention.** Project uses `[Tag] Description` (e.g. `[Fix] ...`) for changelog tooling, rather than `fix: ...`.

### Optional (non-blocking)

Removing `iterator() = default` and `iterator(const iterator &) = default` is harmless today (nothing default-constructs an `iterator`, copy ctor is still implicitly generated). Strictly, dropping the default ctor means `iterator` no longer satisfies the C++17 *LegacyForwardIterator* DefaultConstructible requirement — purely theoretical here. Re-adding `iterator() noexcept = default;` would keep full concept conformance, but I wouldn't block on it.

**Comment by xandris** [comment]
@vstakhov thank you very much for such a thorough review. i think i fixed the issues you pointed out; it's been a very long time since i wrote any C++
